@host = http://localhost:3031
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY4NDk1MDc4LCJleHAiOjE3Njg0OTg2Nzh9._2RPAKXAMUCYQKkp1qDXKG_eBTEUQsFOGz8tPhh0hvE

###
POST {{host}}/users
Content-Type: application/json

{
  "username": "Agus",
  "password": "admin123",
  "role": "0"
}

###
POST {{host}}/users
Content-Type: application/json

{
  "username": "Andi",
  "password": "admin234",
  "role": "0"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "Agus",
  "password": "admin123"
}

###
GET {{host}}/users
Authorization: Bearer {{token}}


###
DELETE {{host}}/users/2
Authorization: Baarer {{token}}

Content-Type: application/json

###
GET {{host}}/users
Authorization: Bearer {{token}}

###
POST  {{host}}/buku
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "judul": "Clean Code",
  "penulis": "Robert C. Martin",
  "penerbit": "Prentice Hall",
  "tahun": "2008",
  "stok": 5
}

###
GET {{host}}/buku
Authorization: Bearer {{token}}

###
GET {{host}}/buku/1
Authorization: Bearer {{token}}

###
PUT {{host}}/buku/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "judul": "Clean Code (Revised)",
  "penulis": "Robert C. Martin",
  "penerbit": "Pearson",
  "tahun": 2010,
  "stok": 10
}

###
DELETE {{host}}/buku/1
Authorization: Bearer {{token}}

###
GET {{host}}/buku
Authorization: Bearer {{token}}