@host = http://localhost:3031

###
POST {{host}}/users
Content-Type: application/json

{
  "username": "Agus",
  "password": "admin123",
  "role": "0"
}

###
POST {{host}}/users
Content-Type: application/json

{
  "username": "Andi",
  "password": "admin234",
  "role": "0"
}

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "Agus",
  "password": "admin123"
}

###
GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18


###
DELETE {{host}}/users/2
Authorization: Baarer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18

Content-Type: application/json

###
GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18

###
POST  {{host}}/buku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18
Content-Type: application/json

{
  "judul": "Clean Code",
  "penulis": "Robert C. Martin",
  "penerbit": "Prentice Hall",
  "tahun": "2008",
  "stok": 5
}

###
GET {{host}}/buku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18

###
GET {{host}}/buku/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18

###
PUT {{host}}/buku/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18
Content-Type: application/json

{
  "judul": "Clean Code (Revised)",
  "penulis": "Robert C. Martin",
  "penerbit": "Pearson",
  "tahun": 2010,
  "stok": 10
}

###
DELETE {{host}}/buku/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18

###
GET {{host}}/buku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZ3VzIiwiaWF0IjoxNzY2NDkyNDA3LCJleHAiOjE3NjY0OTYwMDd9.pQhOPCmXaEPNKewRfQqkuEa2WGb8M5Xxl3n7FSPVP18